InitializationSettings:
  config_id: 1  # Unique configuration id (plotted results will be saved with this id)
  time:
    start_time: 0  # Start time (minutes)
    end_time: 44640  # End time (minutes, 31 days * 24 hours * 60 minutes)
    delta_t: 15  # Time step (minutes)
  passive_consumers_power_setpoints: data/combined_active_power.csv
  grid_topology: data/grid_topology.csv
  initial_conditions:
    heat_pump:
      power_set_point: 100
    room:
      temperature: 15  # Initial temperature in the room.
      outside_temperature: 15  # Temperature outside the room.
      thermal_capacitance: 5000  #6000000 Represents how much heat is needed for a 1°C temperature increase.
      thermal_resistance:   0.01  # 0.0025 Represents how well the room is insulated (higher R = better insulation).
    ev:
      power: 0